title: Ellen Li, Product Designer
email: me@ellen.li
description: Ellen operates at the intersection of product design, technology, and entrepreneurship. She works at Shopify.

baseurl: ""
url: "http://ellen.li"

# content

permalink: /:title
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      # layout: "default"
      is_post: true

# social

twitter_username: ellenxli
github_username: ellenli

# build

sass:
    style: compressed
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
encoding: "utf-8"
