# general

title: Ellen Li, Product Designer
email: me@ellen.li
description: Ellen operates at the intersection of product design, technology, and entrepreneurship. She currently works at Shopify.

baseurl: ""
url: "http://ellen.li"

# content

permalink: /:title
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      # layout: "default"
      is_post: true

# social

twitter_username: ellenxli
github_username:  ellenli

# build

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: minima
encoding:     "utf-8"

# include/exclude

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
lsi: true
google_analytics: UA-27811032-1
